### ISSUE TITLE
普通弹幕无效

### ISSUE THREAD

**Issue by Starrysky-wbk** [champkeh/blive-ws#5]
现在普通弹幕已经无法获取了，只能获取进入房间和送礼物

**Comment by champkeh** [comment]
@Starrysky-wbk 我调试了下，发现B站推送的弹幕消息类型变了，如下图所示：
![image](https://user-images.githubusercontent.com/7316006/205570008-7d2aaeaa-a968-4b29-abbe-7d23b444989a.png)

具体原因不清楚，我调整下代码，按照字符串开头匹配下就可以了

**Comment by Starrysky-wbk** [comment]
好的！非常感谢您的回复，麻烦啦




304875033
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "champkeh/blive-ws"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月5日(星期一) 下午3:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [champkeh/blive-ws] 普通弹幕无效 (Issue #5)





 
@Starrysky-wbk 我调试了下，发现B站推送的弹幕消息类型变了，如下图所示：
 
 
具体原因不清楚，我调整下代码，按照字符串开头匹配下就可以了

**Comment by champkeh** [comment]
已经修复了
